---
title: "Multi-day eval testing"
output: html_notebook
---
```{r}
library('tidyverse')
library('MARSS')
library('tictoc')
library('foreach')
library('doParallel')

# Import the data
path <- '/Users/eric/repos/aud/subject_marss_70_79.csv'
data <- read.csv(path)
subid_list <- unique(data$subid)

# Model definition
init_var<-10
# 3 latent states, no state interactions
B1 <- matrix(list(0),3,3)
diag(B1)<-list("b1","b2","b3")
U1 <- matrix(list("u1","u2","u3"),3,1)
Q1 <- diag(1, 3)
R1 <- matrix(list(0),10,10)
diag(R1)<-list("r1","r2","r3","r4","r5","r6","r7","r8","r9",0.25)
Z1 <- matrix(c(
  "z11", "z21", "z31", "z41", "z51", "z61", "z71", "z81", "z91", "z101",
  "z12", "z22", "z32", "z42", "z52", "z62", "z72", "z82", "z92", "z102",
  "z13", "z23", "z33", "z43", "z53", "z63", "z73", "z83", "z93", "z103"
), 10, 3)
A1 <- "unconstrained"
pi1 <- matrix(0, 3, 1)
V1 = diag(init_var, 3, 3)
model3ni <-list(B = B1, U = U1, Q = Q1, Z = Z1, A = A1, R = R1, x0 = pi1, V0 = V1, tinitx = 1)
# 9 latent states, no state interactions
B1 <- "diagonal and unequal"
U1 <- "unequal"
Q1 <- diag(1, 9)
R1 <- matrix(list(0),10,10)
diag(R1)<-list("r1","r2","r3","r4","r5","r6","r7","r8","r9",0.25)
Z1 <- diag(1,10,9)
Z1[10,] <- c("d1","d2","d3","d4","d5","d6","d7","d8","d9")
A1 <- "unequal"
pi1 <- matrix(0, 9, 1)
V1 = diag(init_var, 9, 9)
model3ni <-list(B = B1, U = U1, Q = Q1, Z = Z1, A = A1, R = R1, x0 = pi1, V0 = V1, tinitx = 1)
fit_model <- function(input_data,input_model){
  tryCatch({em_fit <- MARSS(input_data, model = input_model, control = list(safe=TRUE,maxit = 200,allow.degen=TRUE));
  bfgsfit <- MARSS(input_data, model = input_model, method = "BFGS", inits = em_fit)},
  error=function(e){print("WE GOT PROBLEMS");return(error("problemo"))}
  )
  return(bfgsfit)
}
backup_fit_model <- function(input_data,input_model){
  bfgsfit <- MARSS(input_data, model = input_model, method = "BFGS")
  return(bfgsfit)
}

make_frame <- function(model_name, subject, AIC_val,horizon,t,pred,actual){
  df <- data.frame("model_name"=model_name,"id"=subject,"AIC"=AIC_val,"train_horizon"=horizon,"pred_t"=t,"pred"=pred,"actual"=actual)
  return(df)
}

n.cores <- detectCores() -1
my.cluster <- makeCluster(
  n.cores,
  type="FORK"
)
print(my.cluster)

doParallel::registerDoParallel(cl=my.cluster)
foreach::getDoParRegistered()
foreach::getDoParWorkers()
```

```{r}
data_store = data.frame()
model_name<- "3ni"
horizon_list <- c(60,80)
tic("parallel")
#test<-foreach(subject_idx=19,.combine=rbind.data.frame) %dopar% {
for(subject_idx in c(17)){
  current_id <- subid_list[[subject_idx]]
  # Pull the data associated with the current individual
  current_data <- data[data$subid==current_id,]
  # Convert to a matrix and trim extra rows
  datamat <- t(as.matrix(current_data))
  datamat <- datamat[-c(1,2,3,14),]
  # Create a storage dataframe for this subject
  subject_store <-data.frame()
  for(horizon_idx in 1:length(horizon_list)){
  #foreach(horizon_idx=1:length(horizon_list)) %dopar% {
    horizon<-horizon_list[horizon_idx]
    # Set up the complete data from 1:horizon as model fitting training set
    training <- datamat[,1:horizon]
    # Fit the model
    tryCatch({mlefit <- backup_fit_model(training,model3ni)},
             error=function(e){print("yooooo");next}
    )
    aic_val<-AIC(mlefit)
    # Maximum horizon length for prediction steps
    mhl <- 90-horizon
    horizon_store <- data.frame()
    # Add 1 day of new data at a time and make same-day lapse prediction
    for(hlength in 1:mhl){
      #print(hlength)
      # Start index for new data
      start <- horizon+1
      # End indix for new data
      end <- horizon+hlength
      # Use start and end to create a new data matrix
      new_dat <-as.matrix(datamat[,start:end])
      #print(new_dat)
      # Pull the actual lapse value out of the new data matrix
      actual_lapse <- new_dat[[10,ncol(new_dat)]]
      # Put in NA for use in forecasting
      new_dat[10,ncol(new_dat)]<-NA
      #print(new_dat)
      # Make the prediction (uses the new data to smooth xt-1 and get filtered xt?)
      fr<-predict(mlefit,n.ahead=hlength,newdata=list(y=new_dat),type='ytT')
      output <- fr$pred
      pred_val <- fr$pred[nrow(output),ncol(output)]
      iter_df <- make_frame(model_name,current_id, aic_val,horizon,end,pred_val,actual_lapse)
      horizon_store<-rbind(horizon_store,iter_df)
    }
    subject_store<-rbind(subject_store,horizon_store)
  }
  #return(subject_store)
}
toc()
stopCluster(cl = my.cluster)
```
```{r}
plot(mlefit)
```

```{r}
summary(current_data)
```


