#train.sub
container_image = osdf:///chtc/staging/jjcurtin/train.sif
executable = train.sh
arguments = $(job_num) $(subid)
  
log = $(Cluster).log
error = error/error_$(job_num).err
  
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_remaps = "results_$(job_num).csv = results/results_$(job_num).csv"
on_exit_hold = exitcode != 0
max_retries = 1
transfer_input_files = demo.R, helper_functions.R mle_coef_fit.R data.csv, jobs.csv
max_idle = 1000
request_cpus = 1
request_memory = 50000MB
request_disk = 3000MB
want_campus_pools = TRUE
want_ospool = TRUE
queue job_num,subid from jobs.csv
